/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_dynamodb_all_tables_region": "eu-north-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "review-dev",
            "region": "eu-north-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "playerestapi",
            "endpoint": "https://ujvjkktpj2.execute-api.eu-north-1.amazonaws.com/dev",
            "region": "eu-north-1"
        }
    ]
};


export default awsmobile;
